export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#0b1326',
        'surface-dim': '#060e20',
        'surface-container': '#171f33',
        'surface-container-low': '#131b2e',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-bright': '#31394d',
        primary: '#c4c1fb',
        'primary-dim': '#9e9bd8',
        'primary-container': '#1e1b4b',
        'on-primary': '#2d2a5b',
        secondary: '#4cd7f6',
        'secondary-container': '#03b5d3',
        'on-secondary': '#003640',
        tertiary: '#d0bcff',
        'tertiary-container': '#2a006b',
        success: '#69f0ae',
        warning: '#ffd54f',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c8c5d0',
        'on-primary-container': '#8683ba',
        'on-secondary-container': '#00424e',
        'on-primary-fixed': '#181445',
        outline: '#928f9a',
        'outline-variant': '#47464f',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-in': 'slideIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideIn: {
          '0%': { opacity: '0', transform: 'translateX(-8px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
    },
  },
  plugins: [],
};
